name: Build and publish

on:
  push:
    branches: [master]
    tags:
      - 'v*.*.*'

env:
  NODE_VERSION: 12.x

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install, build, Test
      run: |
        yarn install --frozen-lockfile
        yarn build
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Test
      run: yarn test

  release:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false

  publish:
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        registry-url: 'https://registry.npmjs.org'
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: npm publish

  deploy-website:
    needs: [publish]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Restore build cache
      uses: actions/cache@v2
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Install, build & prepare gallery
      run: |
        cd gallery
        yarn --frozen-lockfile
        yarn build
        echo 'ui.aragon.org' > dist/CNAME
        cp public/favicon.svg dist
    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gallery/dist
